import hashlib,json,pathlib,subprocess
p=pathlib.Path(__file__).resolve().parent;originals=pathlib.Path('/workspace/.continuation/p2-after-070-source-audit/originals');head='552a6f3ab8b16cce49a9cf0de1e247c3ff49e3a9';repo=pathlib.Path('/workspace/rougezhushou');sha=lambda b:hashlib.sha256(b).hexdigest();raw={};sources={}
for name,h in [('uniequip_table','b508483cc87c03d8313f4dd8dfc1b9195bc50385a8dfec51d17e657cb26ffad9'),('battle_equip_table','006687f201a823abf31c6a1c57b2269099bd3ea375c2ec3ae5595cc98a1ec460')]:
 q=originals/(name+'.json');b=q.read_bytes();assert sha(b)==h;raw[name]=json.loads(b);sources[name]={'path':str(q),'sha256':h,'bytes':len(b),'original_game_commit':'a550f5e048bb94e7cdefc6eb97a4091f0c4c7add','reused_existing_public_originals':True,'raw_bytes_rehashed':True,'fresh_download':False}
b=subprocess.check_output(['git','-C',str(repo),'show',head+':rouge/data/catalog.json']);cat=json.loads(b);inventory=[];selectors={}
for op,profile in cat['operators'].items():
 if not profile.get('tokens'):continue
 for module in profile['modules']:
  id=module['id'];entry=raw['uniequip_table']['equipDict'][id];phases=raw['battle_equip_table'][id]['phases'];selectors['battle_equip_table.'+id]={'phases':phases}
  for phase in phases:
   inventory.append({'operator_id':op,'operator_name':profile['name'],'owned_profile_tokens':list(profile['tokens']),'module_id':id,'module_level':phase['equipLevel'],'unlock_original':{'phase':entry['unlockEvolvePhase'],'level':entry['unlockLevel']},'direct_token_attributes':phase['tokenAttributeBlackboard'],'token_parts':[part for part in phase['parts'] if part.get('isToken') is True],'other_parts_targets':[part['target'] for part in phase['parts'] if part.get('isToken') is not True]})
assert len({r['module_id'] for r in inventory})==8 and len(inventory)==24
ws=[r for r in inventory if r['module_id']=='uniequip_002_wisdel'];assert len(ws)==3 and all(not r['direct_token_attributes'] and not r['token_parts'] for r in ws)
(p/'pinned-owned-token-module-selectors.json').write_text(json.dumps(selectors,ensure_ascii=False,indent=2)+'\n')
defer={'wisdel_module':'Pinned three phases contain no direct tokenAttributeBlackboard and no isToken part; named body trait/Good Gifts changes already present. This does not prove absence of other script/inheritance effects. No new repair from these selectors. Resume only with a distinct exact ghost/module binding or current independent event/panel evidence.','wang_cap':'Pinned module has cost-1 and max_deploy_count+1; cost reference already42. Generic Deepcolor TokenCard CFG cannot establish Wang own prefab talent application, own livecap, initialCnt/auto-generated S3 count or dontOccupyMaxDeployCnt. Resume with exact token_10064_wang_stone1 prefab/buff attachment and producer/consumer binding; do not sum held stock to livecap.','mechanist_hidden_barrier':'Pinned rogue_6 token TALENT10_root has interval1/cooldown5/hp_ratio.04/hp_ratio_max.2. Existing26 already records this missing binding; parameters do not establish attachment/current maxHP operand/first pulse/reset/actual alive window. Need exact mcnist_equip_1_3_p3 buff/callback or independent event evidence, no new numeric model.','deepcolor_current_validation':'Pinned SUM-Y directcost/count and token HP candidates already covered by historical public proof; current hotfix/livepanel not reverified. Resume only with independent version-matched livepanel/hotfix evidence; no invented fake fixture or current native claim.'}
receipt={'kind':'readonly remaining summon-module source audit; not a completed numbered section','baseline_head':head,'catalog_sha256':sha(b),'sources':sources,'module_count':8,'phase_count':24,'inventory':inventory,'defer_and_restart_conditions':defer,'no_new_candidate_with_sufficient_untouched_binding':True,'normalized_absence_not_used_to_prove_raw_absence':True,'raw_absence_not_used_to_prove_native_effect_absence':True,'production_edits':0,'native_binary_downloads':0,'private_state_read':False}
(p/'source-inventory-receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'modules':8,'phases':24,'receipt_sha256':sha((p/'source-inventory-receipt.json').read_bytes()),'selectors_sha256':sha((p/'pinned-owned-token-module-selectors.json').read_bytes()),'new_repair_candidate':False}))
